### ISSUE TITLE
Chinese support doesn't work

### ISSUE THREAD

**Issue by agelastic** [dayjaby/yomisama#9] opened 2020-05-06 07:10 UTC
First time using Yomisama. Japanese lookups are ok but Chinese lookups simply don't work, with 中 dictionary turned on in settings. Cedict file is present. When both 日 and 中 turned on, results come only from a Japanese dictionary. Anki 2.1.20 and 2.1.23. What am I missing? Plugin claims Chinese is supported, together with other non-Japanese languages.

**Comment by dayjaby** [comment] 2020-05-06 08:24
Hey! I use it for Chinese all the time right now, can you try only 中 being turned on?

![Screenshot from 2020-05-06 10-22-33](https://user-images.githubusercontent.com/164396/81153793-8d294000-8f83-11ea-8fda-8fb68a4ae28d.png)

Can you confirm that the file cedict_ts.u8 is present in the addon folder?

```
~/.local/share/Anki2/addons21/yomisama/yomi_base/languages/chinese] master(+8/-2) ± ls -al
total 8552
drwxr-xr-x 2 sitebots sitebots    4096 Mär 19 14:16 .
drwxr-xr-x 7 sitebots sitebots    4096 Dez 15 14:03 ..
-rw-r--r-- 1 sitebots sitebots 8734237 Dez 14 16:34 cedict_ts.u8
-rw-r--r-- 1 sitebots sitebots    1599 Mär 19 14:16 dictionary.py
-rw-r--r-- 1 sitebots sitebots     321 Dez 15 13:46 __init__.py
-rw-r--r-- 1 sitebots sitebots    1100 Dez 10 23:00 translate.py
```

**Comment by agelastic** [comment] 2020-05-06 10:16
中 produces output only in "sentences" tab. Same for purely Chinese texts. ![Example](https://user-images.githubusercontent.com/4494796/81165939-3436c780-8fd6-11ea-85ab-801d5aa99a4f.png)

The file exists in the right place, that's what I meant by "cedict file present", sorry. I could be missing some configuration steps?

```
~/Library/Application Support/Anki2/addons21/907186589/yomi_base/languages/chinese

yomi_base/languages/chinese via 🐍 3.7.5
➜ ls -la
total 17088
drwxr-xr-x  6 witt  staff      192  6 May 16:35 .
drwxr-xr-x  9 witt  staff      288  6 May 16:30 ..
-rw-r--r--  1 witt  staff      321  6 May 16:33 __init__.py
-rw-r--r--  1 witt  staff  8734237  5 May 13:35 cedict_ts.u8
-rw-r--r--  1 witt  staff     1599  5 May 13:35 dictionary.py
-rw-r--r--  1 witt  staff     1100  5 May 13:35 translate.py
```

**Comment by dayjaby** [comment] 2020-05-06 12:09
Can you start anki from command line and reproduce the error? The python3 support is very fresh and there might be some error here that is not shown to the user (but in the command line you can see them usually)

**Comment by agelastic** [comment] 2020-05-07 08:44
Hm, lookups work when I run Anki from console. Tried the app again - still doesn't work.
Do you perhaps run Anki only from CLI? The "App" and CLI startup seem to have slightly different exec paths.

logs from: cmdY, lookups, close, cmdY again, close, quit.
```
➜ /Applications/Anki.app/Contents/MacOS/Anki
Qt WebEngine resources not found at . Trying parent directory...
Qt WebEngine resources not found at /Applications/Anki.app/Contents/MacOS/PyQt5/Qt. Trying application directory...
Installed Qt WebEngine locales directory not found at location /qtwebengine_locales. Trying application directory...
[Errno 2] No such file or directory: '/Users/witt/Library/Application Support/Anki2/addons21/907186589/yomi_base/languages/korean/dictionary.db'
Caught exception:
Traceback (most recent call last):
  File "/Users/witt/Library/Application Support/Anki2/addons21/907186589/yomi_base/reader.py", line 250, in moveEvent
    self.preferences['windowPosition'] = event.pos().x(), event.pos().y()
AttributeError: 'MainWindowReader' object has no attribute 'preferences'

Caught exception:
Traceback (most recent call last):
  File "/Users/witt/Library/Application Support/Anki2/addons21/907186589/yomi_base/reader.py", line 250, in moveEvent
    self.preferences['windowPosition'] = event.pos().x(), event.pos().y()
AttributeError: 'MainWindowReader' object has no attribute 'preferences'

Caught exception:
Traceback (most recent call last):
  File "/Users/witt/Library/Application Support/Anki2/addons21/907186589/yomi_base/profiles/movie.py", line 45, in eventFilter
    mp = self.profile.mplayer
AttributeError: 'MovieProfile' object has no attribute 'mplayer'

Caught exception:
Traceback (most recent call last):
  File "/Users/witt/Library/Application Support/Anki2/addons21/907186589/yomi_base/profiles/movie.py", line 45, in eventFilter
    mp = self.profile.mplayer
AttributeError: 'MovieProfile' object has no attribute 'mplayer'

Caught exception:
Traceback (most recent call last):
  File "/Users/witt/Library/Application Support/Anki2/addons21/907186589/yomi_base/profiles/movie.py", line 45, in eventFilter
    mp = self.profile.mplayer
AttributeError: 'MovieProfile' object has no attribute 'mplayer'


yomi_base/languages/chinese via 🐍 3.7.5 took 3m 53s
➜
```

Update: and Anki crashed

**Comment by agelastic** [comment] 2020-05-11 05:57
Is there anything I'm doing wrong here or is it a genuine bug?

**Comment by dayjaby** [comment] 2020-05-11 06:27
Give me one day to fix the issues that you reported. My code seems to make the following assumptions about your environment:

- the korean db is there
- you have mplayer installed

I will deactivate the movie profile altogether, since it is not properly tested in python 3.

Thanks for your patience and excellent error reporting!

**Comment by agelastic** [comment] 2020-05-11 06:38
These two bugs don't seem to be related to the problem I'm having. I'll try the plugin from this repo later in any case.

Moreover, Korean db probably wasn't included in the published plugin on ankiweb. And mplayer *is* present, from homebrew.

```
➜ which mplayer
/usr/local/bin/mplayer

➜ mplayer
MPlayer 1.4-4.2.1 (C) 2000-2019 MPlayer Team
Usage:   mplayer [options] [url|path/]filename
…
➜ brew info mplayer
mplayer: stable 1.4 (bottled), HEAD
UNIX movie player
…
```

**Comment by dayjaby** [comment] 2020-05-12 07:59
The two errors should be resolved now. Can you try it? I did not upload to Anki yet, but with the following instructions you are able to get the most up to date code:

```
cd /Users/witt/Library/Application Support/Anki2/addons21/907186589
git init
git remote add origin https://github.com/dayjaby/yomisama
git pull origin master
```

Then try Anki as you used to do.

**Comment by dayjaby** [comment] 2020-05-12 08:58
Uploaded the new version to https://ankiweb.net/shared/info/907186589

**Comment by agelastic** [comment] 2020-05-13 06:53
I updated the plugin from ankiweb - similar story. Lookups work when Anki is started on CLI and dont when it's ran as an app. It is still looking for korean.db

```
Anki.app/Contents/MacOS
➜ ./Anki
Qt WebEngine resources not found at . Trying parent directory...
Qt WebEngine resources not found at /Applications/Anki.app/Contents/MacOS/PyQt5/Qt. Trying application directory...
Installed Qt WebEngine locales directory not found at location /qtwebengine_locales. Trying application directory...
[Errno 2] No such file or directory: '/Users/witt/Library/Application Support/Anki2/addons21/907186589/yomi_base/languages/korean/dictionary.db'

Anki.app/Contents/MacOS took 1m 24s
➜
```

Screenshots:
1. starting Anki from CLI 
![Screen Shot 2020-05-13 at 4 47 50 pm](https://user-images.githubusercontent.com/4494796/81780567-115a6500-953a-11ea-8d41-fce428108c87.png)

2. starting it as an app:
![Screen Shot 2020-05-13 at 4 53 49 pm](https://user-images.githubusercontent.com/4494796/81780734-5f6f6880-953a-11ea-9a65-289572a49dbe.png)

**Comment by dayjaby** [comment] 2024-07-05 16:50
Sorry for not having this issue resolved :( hope you are well. closing this for now

**Closed as completed by dayjaby** 2024-07-05 16:50 UTC
